[versions]
agp = "8.13.1"
kotlin = "2.2.21"
ksp = "2.2.0-2.0.2"
work-ktx = "2.11.0"
onesignal = "5.4.1"
androidx-core-ktx = "1.17.0"
compose = "1.9.5"
navigation-compose = "2.9.6"
lifecycle = "2.10.0"
activity-compose = "1.12.0"
accompanist = "0.36.0"
accompanist-permissions = "0.37.3"
retrofit = "3.0.0"
moshi = "1.15.2"
datastore = "1.2.0"
hilt = "2.57.2"
hilt-navigation = "1.3.0"
coil-compose = "2.7.0"
desugar-jdk-libs = "2.1.5"
junit = "4.13.2"
androidx-test = "1.3.0"
espresso = "3.7.0"
material = "1.4.0"
kotlinx-serialization = "1.9.0"
play-services-location = "21.3.0"
adhan = "0.0.6"
splashscreen = "1.2.0"
google-maps = "6.12.2"
mapsecrets = "2.0.1"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
jetbrains-kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
dagger-hilt-android = { id = "dagger.hilt.android.plugin"}
kotlinX-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

[libraries]
hilt-android-gradle-plugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt" }
work-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "work-ktx" }
onesignal = { module = "com.onesignal:OneSignal", version.ref = "onesignal" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core-ktx" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-material = { module = "androidx.compose.material3:material3", version.ref = "material" }
compose-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "compose" }
compose-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation-compose" }
lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
accompanist-pager = { module = "com.google.accompanist:accompanist-pager", version.ref = "accompanist" }
accompanist-pager-indicators = { module = "com.google.accompanist:accompanist-pager-indicators", version.ref = "accompanist" }
accompanist-swiperefresh = { module = "com.google.accompanist:accompanist-swiperefresh", version.ref = "accompanist" }
accompanist-navigation-animation = { module = "com.google.accompanist:accompanist-navigation-animation", version.ref = "accompanist" }
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist-permissions" }
play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "play-services-location" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-converter-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }
moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
moshi-adapters = { module = "com.squareup.moshi:moshi-adapters", version.ref = "moshi" }
moshi-kotlin-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
dagger-hilt = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt-navigation" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil-compose" }
desugar-jdk-libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar-jdk-libs" }
junit = { module = "junit:junit", version.ref = "junit" }
androidx-test-ext = { module = "androidx.test.ext:junit", version.ref = "androidx-test" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
adhan = { module = "com.batoulapps.adhan:adhan2", version.ref = "adhan" }
splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "splashscreen" }
google-maps = { module = "com.google.maps.android:maps-compose", version.ref = "google-maps" }
maps-secrets-plugin = { module = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin:secrets-gradle-plugin", version.ref = "mapsecrets" }

[bundles]
accompanist = ["accompanist-pager", "accompanist-pager-indicators", "accompanist-swiperefresh","accompanist-navigation-animation","accompanist-permissions"]
compose = ["compose-ui", "compose-material", "compose-tooling-preview", "compose-runtime"]
lifecycle = ["lifecycle-viewmodel","lifecycle-runtime"]
retrofit = ["retrofit","retrofit-converter-moshi"]
moshi = ["moshi","moshi-adapters"]